steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'asia-south1-docker.pkg.dev/doorships/betteruptime/api', '-f', 'Dockerfile.api', '.']
images:
  - 'asia-south1-docker.pkg.dev/doorships/betteruptime/api'