# ------------------------------
# 1. Base image (Bun official)
# ------------------------------
FROM oven/bun:1

# ------------------------------
# 2. Set working directory
# ------------------------------
WORKDIR /app

# ------------------------------
# 3. Copy entire monorepo
# ------------------------------
COPY . .

# ------------------------------
# 4. Move into API folder
# ------------------------------
WORKDIR /app/apps/api/worker

# ------------------------------
# 5. Install API dependencies
# ------------------------------
RUN bun install

# ------------------------------
# 6. Cloud Run expects the server
#    to listen on 0.0.0.0:$PORT
# ------------------------------
ENV PORT=8080
ENV DATABASE_URL=postgresql://neondb_owner:npg_IcfqaS62BRgY@ep-divine-fire-a129v6xb-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
ENV JWT_SECRET=Gungun@2005
ENV REGION_ID ="2005"
ENV WORKER_ID="india-2"
ENV REDIS_URL=rediss://default:AV6iAAIncDI2YmM0NTc3MmY5Mzc0OTcyODI5Y2I0ZTgwMmU3OWQ1YnAyMjQyMjY@evolving-liger-24226.upstash.io:6379



# (Cloud Run sets PORT at runtime automatically: 8080, 8081 etc.)
EXPOSE 8080

# ------------------------------
# 7. Start API server
# ------------------------------
CMD ["bun", "index.ts"]
